# Generated by Django 4.1.1 on 2022-11-05 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedcards',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
