# Generated by Django 4.1.1 on 2022-11-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0002_alter_usedcards_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedcards',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
