# Generated by Django 4.1.1 on 2022-11-05 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0003_usedcards_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedcards',
            name='amount',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
