# Generated by Django 4.1.4 on 2023-03-28 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0004_usedcards_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='usedcards',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
