# Generated by Django 4.1.4 on 2023-04-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0005_usedcards_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationreg',
            name='status',
            field=models.DateField(auto_now=True),
        ),
    ]
