# Generated by Django 4.1.4 on 2023-04-13 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_app', '0008_alter_donationreg_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationreg',
            name='status',
        ),
    ]
